routes/main.py
from flask import Blueprint, render_template


main = Blueprint('main', __name__, static_folder='static', template_folder='templates')

@main.route('/')
def home():
    col = ['#d9d9d9', 'white']
    bottom_menu = 'y'
    return render_template('animations.html', col=col, bottom_menu=bottom_menu)


@main.route('/character_design')
def character_design():
    col = ['white','#d9d9d9']
    bottom_menu = 'y'
    return render_template('character_design.html', col=col, bottom_menu=bottom_menu)

routes/templates/animations.html
{% extends "index.html" %}
{% block inner_content %}

<div class="col-12 col-s-12">
    <div class="youtube-video-container">
        <iframe class="youtube-video" width="80%" src="https://www.youtube.com/embed/ulHJ2kzG8SI?si=zkuBrUer6t4QI6eJ"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>

    <div class="youtube-video-container">
        <iframe class="youtube-video" width="80%" src="https://www.youtube.com/embed/gTw_d4_L6j4?si=zkuBrUer6t4QI6eJ"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
    <div class="youtube-video-container">
        <iframe class="youtube-video" width="80%" src="https://www.youtube.com/embed/RohxCgnoX_o?si=Sl4Wxn3GVNfcIziU"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
    <div class="youtube-video-container">
        <iframe class="youtube-video" width="80%" src="https://www.youtube.com/embed/l9n66DWKCqk?si=bd0NT0KUvqp8nl47"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
    <div class="youtube-video-container">
        <iframe class="youtube-video" width="80%" src="https://www.youtube.com/embed/9b3BbV8pHZY?si=wQDlZ7xJpx1RS8Sm"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
    <div class="youtube-video-container">
        <iframe class="youtube-video" width="80%" src="https://www.youtube.com/embed/g0XEsC3Ff58?si=M1W9IQ_bL8OfGodD"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
</div>

{% endblock %}

routes/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Shwetabh Suman</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css')}}"
    />
<!--    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.home') }}"><b>SHWETABH SUMAN</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent":q
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.character_design') }}">Character Design</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.home') }}">Animation</a>
        </li>

      </ul>
    </div>
  </div>
</nav>
    {% block content %}
    {% endblock %}
    <div style="background:#2b2b2b;">
        <h6 style="color:rgba(255,255,255,0.5); text-align:center; padding: 5vh;">&#169; 2024 | Shwetabh Suman | All Ideas & Illustrators are copyrighted | All Rights reserved</h6>
    </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<footer>

</footer>
  </body>
</html>

routes/templates/character_design.html
{% extends "index.html" %}
{% block inner_content %}

<!----------------------------------------- BLINDO --------------------------------------------------->

<div class="col-12 col-s-12" style="background:black; color:white; padding:2% 0%;">
    <h1 style="text-align: center;"> BLINDO </h1>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Blindo/Untitled-1.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Blindo/Expression-Sheet---Blindo.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Blindo/Turnaround---Blindo.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Blindo/Wing-Poses---Blindo.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Blindo/Pose-Sheet---Blindo.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Blindo/Hand-Design---Blindo.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Blindo/Costume-Sheet---Blindo.jpg" width="70%">
    </div>
</div>


<!-------------------------------------- ANDRIOTTI ----------------------------------------->

<div class="col-12 col-s-12" style="background:black; color:white; padding:2% 0%;">
    <h1 style="text-align: center;"> ANDRIOTTI </h1>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Andriotti/Andriotti-Rough.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Andriotti/Turnaround---Andriotti.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Andriotti/Wing-Poses---Andriotti.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Andriotti/Costume-Sheet---Andriotti.jpg" width="70%">
    </div>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Andriotti/Andriotti_Rig_Model.jpg" width="70%">
    </div>
</div>

<!-------------------------------------- CAUTIO ----------------------------------------->
<div class="col-12 col-s-12" style="background:black; color:white; padding:2% 0%;">
    <h1 style="text-align: center;"> CAUTIO </h1>
</div>
<div class="col-12 col-s-12">
    <div class="center">
        <img src="static/images/characters/Cautio/Cautio-and-Books.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Cautio-Rig-Model2.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Body-Rough-Plan.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Cautio-head-plan-board-1.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Eyes-and-Ears.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Specs-Choices.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Cautio-Wings.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Poses-&-Expressions.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/Cautio-hand-poses.jpg" width="70%">
    </div>
    <div class="center">
        <img src="static/images/characters/Cautio/For-design-bg.jpg" width="70%">
    </div>
</div>

{% endblock %}

routes/templates/index.html
{% extends "base.html" %}
{% block content %}

<style>
    .hero {
        width: 100%;
        background-image: linear-gradient(rgba(0,0,0,.5), rgba(0,0,0,.5)), url('../static/images/environment_concept/fish_girl_low_web.jpg');
        background-size: cover;
        background-repeat: no-repeat;
<!--        aspect-ratio: 3 / 1;-->
        height: auto;
        top: 0px;
        bottom: 0px;
        color: white;
        margin-bottom: 2%;
    }

</style>
<body>
<div class="row">
    <div class="col-12, col-s-12 hero">
        <h1 style="text-align: center; padding:8% 0% 0% 0%;">2D Animation</h1>
        <h5 style="text-align: center; padding: 3% 20% 8% 20%; line-height: 2rem; opacity:0.8; font-family: 'Georgia';">
            With expertize in <b>Toon Boom Harmony</b>, <b>Storyboarder Pro</b>, <b>Photoshop</b> and <b>Clip Studio Paint</b>
            I can create character designs, 2D animations and Storyboards. <br>
            In 2D, the jobs I can do are Character design, model sheets, storyboards and animatics, rigs, background illustration, animation (both
            frame-by-frame hand-drawn and cut-out), compositing and vfx (in Toon Boom Harmony), and basic level sound editing also. <br>
            Medium level video editing on <b>Da Vinci </b> and 3D models for import into Toon Boom Harmony are plus.
        </h5>
    </div>

    {% block inner_content %}
    {% endblock %}
</div>


{% endblock %}